-- Run this once in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique not null,
  full_name text,
  premium_active boolean not null default false,
  referral_code text unique not null default encode(gen_random_bytes(6),'hex'),
  referral_verified_count integer not null default 0 check (referral_verified_count >= 0),
  discount_rewards_used integer not null default 0 check (discount_rewards_used >= 0),
  premium_until timestamptz,
  stripe_customer_id text unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.profiles enable row level security;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles(id,email,full_name)
  values(new.id, lower(new.email), coalesce(new.raw_user_meta_data->>'full_name',''))
  on conflict (id) do update set email=excluded.email, full_name=excluded.full_name;
  return new;
end; $$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();

drop policy if exists "users can read own profile" on public.profiles;
create policy "users can read own profile" on public.profiles for select using (auth.uid() = id);
-- No client insert/update/delete policies: Premium/admin fields are server-only.

-- Backfill accounts that already existed before this schema was installed.
insert into public.profiles(id,email,full_name)
select id, lower(email), coalesce(raw_user_meta_data->>'full_name','')
from auth.users
where email is not null
on conflict (id) do nothing;

create table if not exists public.referrals (
  id bigint generated by default as identity primary key,
  inviter_user_id uuid not null references public.profiles(id) on delete cascade,
  referred_user_id uuid not null unique references public.profiles(id) on delete cascade,
  referral_code text not null,
  created_at timestamptz not null default now()
);
alter table public.referrals enable row level security;
drop policy if exists "users can read own referrals" on public.referrals;
create policy "users can read own referrals" on public.referrals for select using (auth.uid() = inviter_user_id or auth.uid() = referred_user_id);
