import {useEffect,useMemo,useState} from 'react';
import {ADMIN_EMAIL,useApp} from '../context/AppState';
import {useReferral} from '../context/ReferralEngine';
import Icon from '../components/Icon';
import AccountModal from '../components/AccountModal';
import ThemeManager from '../components/ThemeManager';

export default function Admin(){
  const app=useApp();const r=useReferral();
  const [accountOpen,setAccountOpen]=useState(false);const [target,setTarget]=useState('');const [message,setMessage]=useState('');
  const [users,setUsers]=useState([]);const [loadingUsers,setLoadingUsers]=useState(false);const [userError,setUserError]=useState('');const [busyEmail,setBusyEmail]=useState('');const [query,setQuery]=useState('');
  const loadUsers=async()=>{if(!app.authSession?.access_token)return;setLoadingUsers(true);setUserError('');try{const res=await fetch('/api/admin-users',{headers:{Authorization:`Bearer ${app.authSession.access_token}`}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Unable to load users.');setUsers(Array.isArray(data.users)?data.users:[]);}catch(err){setUserError(err.message||'Unable to load users.');}finally{setLoadingUsers(false);}};
  useEffect(()=>{loadUsers();},[app.authSession?.access_token]);
  const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return q?users.filter(u=>`${u.name} ${u.email}`.toLowerCase().includes(q)):users;},[users,query]);
  const grant=async duration=>{try{const email=target||app.user.email;await app.grantPremium(email,duration);setMessage(`Premium granted to ${email}: ${duration}`);setTarget('');await loadUsers();}catch(err){setMessage(err.message||'Unable to grant Premium.')}};
  const revoke=async email=>{if(!window.confirm(`Revoke Premium from ${email}?`))return;setBusyEmail(email);setMessage('');try{const res=await fetch('/api/admin-revoke',{method:'POST',headers:{Authorization:`Bearer ${app.authSession.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({email})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Unable to revoke Premium.');setMessage(`Premium revoked from ${email}.`);await loadUsers();}catch(err){setMessage(err.message||'Unable to revoke Premium.');}finally{setBusyEmail('');}};
  if(!app.isAdmin)return <div className="page"><div className="panel admin-login"><span className="eyebrow">ADMIN ACCESS</span><h1>Owner access</h1><p className="sub">Sign in with the owner account to open the private admin area.</p><div className="owner-email"><Icon name="user" size={17}/><strong>{ADMIN_EMAIL}</strong></div><button className="primary full" onClick={()=>setAccountOpen(true)}><Icon name="user"/>Sign in as owner</button><small className="help">Admin access is restricted to the authenticated owner email.</small></div><AccountModal open={accountOpen} onClose={()=>setAccountOpen(false)}/></div>;
  return <div className="page">
    <div className="page-top"><div><div className="eyebrow">ADMIN</div><h1>Owner control center.</h1><p className="sub">Testing tools, Premium controls and a live view of SoloPro accounts.</p></div><span className="admin-badge">FULL ACCESS</span></div>
    <div className="stat-cards"><Stat label="Users" value={users.length||'—'}/><Stat label="Premium" value={users.filter(u=>u.premiumActive).length||'0'}/><Stat label="New referrals" value={r.count}/><Stat label="Discount months" value={r.discounts.length}/></div>
    <section className="panel"><div className="panel-head"><div><h2>Premium controls</h2><p>Grant Premium without payment for testing.</p></div><Icon name="crown"/></div><label className="admin-target">User email<input value={target} onChange={e=>setTarget(e.target.value)} placeholder="user@example.com"/></label><div className="admin-actions"><button className="ghost-btn" onClick={()=>grant('1 month')}><Icon name="check"/>Grant 1 month</button><button className="ghost-btn" onClick={()=>grant('3 months')}><Icon name="check"/>Grant 3 months</button><button className="ghost-btn" onClick={()=>grant('1 year')}><Icon name="check"/>Grant 1 year</button><button className="primary" onClick={()=>grant('unlimited')}><Icon name="crown"/>Grant unlimited</button></div>{message&&<div className="notice"><Icon name="check"/>{message}</div>}</section>
    <section className="panel admin-users-panel"><div className="panel-head"><div><h2>SoloPro users</h2><p>Account directory visible only to the owner.</p></div><button className="ghost-btn" onClick={loadUsers} disabled={loadingUsers}><Icon name="spark" size={14}/>{loadingUsers?'Refreshing…':'Refresh'}</button></div><div className="admin-user-toolbar"><div className="search"><Icon name="search" size={14}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name or email"/></div><span>{filtered.length} shown</span></div>{userError&&<div className="notice admin-user-error"><Icon name="check"/>{userError}</div>}{loadingUsers&&users.length===0?<div className="admin-users-empty">Loading users…</div>:filtered.length===0?<div className="admin-users-empty">No users found.</div>:<div className="admin-user-list">{filtered.map(user=><div className="admin-user-row" key={user.id}><div className="admin-user-avatar"><Icon name="user" size={15}/></div><div className="admin-user-main"><strong>{user.name||'Unnamed user'}</strong><span>{user.email}</span></div><div className="admin-user-status">{user.online&&<span className="online-dot" title="Online"/>}<span>{user.online?'Online':'Offline'}</span></div><div className={`admin-user-premium ${user.premiumActive?'active':''}`}><Icon name="crown" size={12}/>{user.premiumActive?'Premium':'Free'}</div>{user.premiumActive&&<button className="ghost-btn admin-revoke-btn" disabled={busyEmail===user.email} onClick={()=>revoke(user.email)}>{busyEmail===user.email?'Revoking…':'Revoke Premium'}</button>}</div>)}</div>}</section>
    <ThemeManager/>
    <section className="panel"><div className="panel-head"><div><h2>Admin identity</h2><p>{ADMIN_EMAIL}</p></div></div><div className="info-row"><span>Role</span><strong>ADMIN</strong></div><div className="info-row"><span>Premium</span><strong>Free / unlimited</strong></div><div className="info-row"><span>Advertising</span><strong>Disabled</strong></div><button className="danger-btn" onClick={()=>app.signOut()}><Icon name="user"/>Sign out of owner account</button></section>
  </div>
}
function Stat({label,value}){return <div className="stat-card"><span>{label}</span><strong>{value}</strong></div>}
