import {useMemo,useState} from 'react';
import {useApp,currencyCodeFor,COUNTRIES} from '../context/AppState';
import {useReferral} from '../context/ReferralEngine';
import {createTranslator} from '../i18n';
import Icon from '../components/Icon';
import Flag from '../components/Flag';
import Modal from '../components/Modal';
import InviteModal from '../components/InviteModal';
import ThemeCard from '../components/ThemeCard';
import AdBanner from '../components/AdBanner';
import TrendChart from '../components/TrendChart';
import PremiumInsights from '../components/PremiumInsights';

function greeting(countryCode,t){const zones={IT:'Europe/Rome',FR:'Europe/Paris',DE:'Europe/Berlin',ES:'Europe/Madrid',PL:'Europe/Warsaw',GB:'Europe/London',CH:'Europe/Zurich',US:'America/New_York',CA:'America/Toronto',JP:'Asia/Tokyo',KR:'Asia/Seoul',AU:'Australia/Sydney',NZ:'Pacific/Auckland',SG:'Asia/Singapore',AE:'Asia/Dubai'};const h=Number(new Intl.DateTimeFormat('en',{hour:'numeric',hour12:false,timeZone:zones[countryCode]||undefined}).format());return h<5?t('goodNight'):h<12?t('goodMorning'):h<18?t('goodAfternoon'):t('goodEvening')}
export default function Dashboard(){const app=useApp();const ref=useReferral();const t=createTranslator(app.language);const [countryOpen,setCountryOpen]=useState(false);const [invite,setInvite]=useState(null);const [quick,setQuick]=useState(null);const [form,setForm]=useState({amount:'',materialCost:'',extraExpense:'',service:t('defaultService')});const now=new Date();const customIncome=Array.isArray(app.financialIncome)?app.financialIncome:[];const customExpenses=Array.isArray(app.financialExpenses)?app.financialExpenses:[];const inMonth=x=>{const d=new Date(x.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();};const monthIncome=customIncome.filter(inMonth);const monthExpenses=customExpenses.filter(inMonth);const revenue=app.monthlyServices.reduce((s,x)=>s+Number(x.amount||0),0)+monthIncome.reduce((s,x)=>s+Number(x.amount||0),0);const variableExpenses=app.monthlyServices.reduce((s,x)=>s+Number(x.materialCost||0)+Number(x.extraExpense||0),0)+monthExpenses.reduce((s,x)=>s+Number(x.amount||0),0);const fixedMonthly=app.fixedExpensePeriod==='weekly'?Number(app.fixedExpenses||0)*52/12:Number(app.fixedExpenses||0);const expenses=variableExpenses+fixedMonthly;const tax=app.taxMode==='reserve'?Math.max(0,revenue-variableExpenses)*Number(app.taxRate||0):0;const net=revenue-expenses-tax;const recent=useMemo(()=>[...app.monthlyServices].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,4),[app.monthlyServices]);const money=n=>new Intl.NumberFormat(app.country.locale,{style:'currency',currency:currencyCodeFor(app.country),maximumFractionDigits:2}).format(n||0);const displayClients=app.clients;const submitQuick=e=>{e.preventDefault();if(!quick)return;app.addService({clientId:quick.id,clientName:quick.name,service:form.service,amount:Number(form.amount)||0,materialCost:Number(form.materialCost)||0,extraExpense:Number(form.extraExpense)||0});setQuick(null);setForm({amount:'',materialCost:'',extraExpense:'',service:t('defaultService')});};
 return <div className="page"><div className="page-top"><div><div className="eyebrow">{greeting(app.countryCode,t)}</div><h1>{t('welcome')}{app.user.name?`, ${app.user.name}`:''}</h1><p className="sub">{t('snapshot')} {app.country.name}.</p></div><button className="location-switch" onClick={()=>setCountryOpen(true)}><span>{app.country.name}{app.stateProfile?` — ${app.stateProfile.name}`:''}</span><Icon name="arrow" size={15}/></button></div>
 <section className="profit-card-main"><ThemeCard theme={app.activeTheme} country={app.country} showCountryName={app.activeTheme==='country'&&app.showCountryName} flagAnimation={app.flagAnimation} compact/><div className="profit-overlay"><div className="profit-card-top"><span>{t('monthlyNetAvailable')}</span><span className="live-pill"><i/> {t('liveEstimate')}</span></div><div className="profit-value">{money(net)}</div><div className="profit-divider"/><div className="profit-details"><span>{t('revenue')}: {money(revenue)}</span><span>{t('otherExpenses')}: -{money(expenses)}</span><span>{t('taxReserve')}: -{money(tax)}</span></div><div className="country-line"><Flag code={app.country.flag}/><span>{app.country.name}{app.stateProfile?` — ${app.stateProfile.name}`:''}</span><span className="rate">{app.taxMode==='reserve'?Math.round(app.taxRate*100)+'% tax':t('taxOff')}</span></div></div></section>
 <div className="dashboard-grid"><section className="panel retainer-panel"><div className="panel-head"><div><h2>{t('clientRetainer')}</h2><p>{t('invitePeopleAttach')}</p></div><button className="round-btn" onClick={()=>setInvite({})}><Icon name="plus" size={20}/></button></div>{displayClients.length===0?<div className="empty"><Icon name="users" size={25}/><strong>{t('noClientsYet')}</strong><span>{t('sampleInviteDisappear')}</span><button className="pink-btn" onClick={()=>window.location.href='/clients'}>{t('addClient')}</button></div>:<div className="client-list">{displayClients.map(c=><div className="client-card" key={c.id}><div className="client-main"><div className="avatar">{c.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><strong>{c.name}</strong><p>{c.email||c.phone||t('noContactSaved')}</p></div></div><div className="client-actions"><button className="ghost-btn" onClick={()=>setQuick(c)}><Icon name="plus" size={15}/>{t('recordService')}</button><button className="pink-btn" onClick={()=>setInvite(c)}><Icon name="send" size={15}/>{t('invite')}</button></div></div>)}</div>}</section>
 <section className="panel summary-panel"><div className="panel-head"><div><h2>{t('thisMonth')}</h2><p>{t('incomeExpensePulse')}</p></div><Icon name="chart" size={21}/></div><div className="metric-list"><div><span>{t('revenue')}</span><strong>{money(revenue)}</strong></div><div><span>{t('otherExpenses')}</span><strong>-{money(expenses)}</strong></div><div><span>{t('taxReserve')}</span><strong>-{money(tax)}</strong></div><div className="metric-total"><span>{t('estimatedNet')}</span><strong>{money(net)}</strong></div></div><div className="summary-note">{app.taxMode==='reserve'?t('taxReserveOnNote'):t('taxReserveOffNote')}</div><a className="text-link" href="/earnings">{t('manageIncomeExpenses')} <Icon name="arrow" size={14}/></a></section></div>
 <TrendChart services={app.services} country={app.country} locale={app.country.locale} taxRate={app.taxMode==='reserve'?app.taxRate:0}/>
 <PremiumInsights />
 <section className="panel recent-panel"><div className="panel-head"><div><h2>{t('recentWork')}</h2><p>{t('serviceRecordsUpdate')}</p></div><a className="text-link" href="/earnings">{t('earnings')} <Icon name="arrow" size={14}/></a></div>{recent.length===0&&monthIncome.length===0&&monthExpenses.length===0?<div className="empty"><Icon name="spark" size={25}/><strong>{t('noRecordsYet')}</strong><span>{t('addServiceIncomeExpense')}</span></div>:<div className="table-list">{recent.map(x=><div className="table-row" key={x.id}><div><strong>{x.service}</strong><small>{x.clientName||t('unassigned')} — {new Date(x.date).toLocaleDateString()}</small></div><span>{money(x.amount)}</span><b>{money((Number(x.amount)||0)-(Number(x.materialCost)||0)-(Number(x.extraExpense)||0))}</b></div>)}{monthIncome.slice(0,4).map(x=><div className="table-row" key={'income-'+x.id}><div><strong>{x.label}</strong><small>{t('otherIncome')} — {new Date(x.date).toLocaleDateString()}</small></div><span>{money(x.amount)}</span><b>{money(x.amount)}</b></div>)}{monthExpenses.slice(0,4).map(x=><div className="table-row" key={'expense-'+x.id}><div><strong>{x.label}</strong><small>{t('expense')} — {new Date(x.date).toLocaleDateString()}</small></div><span>-{money(x.amount)}</span><b>-{money(x.amount)}</b></div>)}</div>}</section>
 {!app.premiumActive&&<AdBanner />}
 <div style={{display:'flex',justifyContent:'center',margin:'24px 0'}}><a href="https://www.producthunt.com/products/solopro?embed=true&utm_source=badge-featured&utm_medium=badge&utm_campaign=badge-solopro" target="_blank" rel="noopener noreferrer"><img alt="SoloPro - Know your real profit. Run your business smarter. | Product Hunt" width="250" height="54" src="https://api.producthunt.com/widgets/embed-image/v1/featured.svg?post_id=1242071&theme=light&t=1788897182277" /></a></div>
 <section className="referral-offer"><div className="offer-copy"><span className="eyebrow">SOLOPRO REWARD</span><h2>{t('discountTitle')}</h2><p>{app.localizePrices(t('discountIntro'))}</p><small>{ref.count} / 7 {t('verifiedProgress')} · {t('premiumMonth')}.</small></div><div className="offer-action"><span className="old-price">{app.formatUsdPrice(8.99)} / {t('monthly')}</span><strong>{app.formatUsdPrice(2.99)}</strong><button className="primary" onClick={()=>setInvite({__referral:true})}>{t('seeHow')}</button><small>{ref.next===7?t('nextRewardReady'):ref.next+' '+t('newUsers')}</small></div></section>
 <Modal open={countryOpen} onClose={()=>setCountryOpen(false)} title={t('quickCountrySwitch')} wide><p className="modal-sub">{t('changingCountryLanguage')}</p><div className="country-select-grid">{COUNTRIES.map(c=><button className={app.countryCode===c.code?'country-option selected':'country-option'} key={c.code} onClick={()=>{app.setCountry(c.code,true);setCountryOpen(false)}}><Flag code={c.flag}/><span>{c.name}</span>{app.countryCode===c.code&&<Icon name="check" size={16}/>}</button>)}</div></Modal>
 <Modal open={!!quick} onClose={()=>setQuick(null)} title={quick?.name?`${t('recordService')} — ${quick.name}`:t('recordService')}><form onSubmit={submitQuick} className="form-stack"><label>{t('service')}<input required value={form.service} onChange={e=>setForm({...form,service:e.target.value})}/></label><label>{t('revenue')}<input required type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></label><label>{t('materials')}<input type="number" min="0" step="0.01" value={form.materialCost} onChange={e=>setForm({...form,materialCost:e.target.value})}/></label><label>{t('otherExpenses')}<input type="number" min="0" step="0.01" value={form.extraExpense} onChange={e=>setForm({...form,extraExpense:e.target.value})}/></label><button className="primary full">{t('save')}</button></form></Modal>
 <InviteModal open={!!invite} onClose={()=>setInvite(null)} clientName={invite?.name||''}/></div>;
}