import {useMemo,useState} from 'react';
import {useApp,currencyCodeFor,COUNTRIES} from '../context/AppState';
import {useReferral} from '../context/ReferralEngine';
import {createTranslator} from '../i18n';
import Icon from '../components/Icon';
import Flag from '../components/Flag';
import Modal from '../components/Modal';
import InviteModal from '../components/InviteModal';
import ThemeCard from '../components/ThemeCard';
import TrendChart from '../components/TrendChart';
import AdBanner from '../components/AdBanner';

function greeting(countryCode){const zones={IT:'Europe/Rome',FR:'Europe/Paris',DE:'Europe/Berlin',ES:'Europe/Madrid',PL:'Europe/Warsaw',GB:'Europe/London',CH:'Europe/Zurich',US:'America/New_York',CA:'America/Toronto',JP:'Asia/Tokyo',KR:'Asia/Seoul',AU:'Australia/Sydney',NZ:'Pacific/Auckland',SG:'Asia/Singapore',AE:'Asia/Dubai'};const h=Number(new Intl.DateTimeFormat('en',{hour:'numeric',hour12:false,timeZone:zones[countryCode]||undefined}).format());return h<5?'Good night':h<12?'Good morning':h<18?'Good afternoon':'Good evening'}
export default function Dashboard(){const app=useApp();const ref=useReferral();const t=createTranslator(app.language);const [countryOpen,setCountryOpen]=useState(false);const [invite,setInvite]=useState(null);const [quick,setQuick]=useState(null);const [form,setForm]=useState({amount:'',materialCost:'',extraExpense:'',service:'Service'});const recent=useMemo(()=>[...app.monthlyServices].sort((a,b)=>new Date(b.date)-new Date(a.date)).slice(0,4),[app.monthlyServices]);const money=n=>new Intl.NumberFormat(app.country.locale,{style:'currency',currency:currencyCodeFor(app.country),maximumFractionDigits:2}).format(n||0);const displayClients=app.clients;const submitQuick=e=>{e.preventDefault();if(!quick)return;app.addService({clientId:quick?.id,clientName:quick?.name,service:form.service,amount:Number(form.amount)||0,materialCost:Number(form.materialCost)||0,extraExpense:Number(form.extraExpense)||0});setQuick(null);setForm({amount:'',materialCost:'',extraExpense:'',service:'Service'});};
 return <div className="page"><div className="page-top"><div><div className="eyebrow">{greeting(app.countryCode)}</div><h1>{t('welcome')}{app.user?.name?`, ${app.user?.name}`:''}</h1><p className="sub">{t('snapshot')} {app.country?.name}.</p></div><button className="location-switch" onClick={()=>setCountryOpen(true)}><span>{app.country?.name}{app.stateProfile?` • ${app.stateProfile?.name}`:''}</span><Icon name="arrow" size={15}/></button></div>
 <section className="profit-card-main"><ThemeCard theme={app.activeTheme} country={app.country} showCountryName={app.activeTheme==='country'&&app.showCountryName} flagAnimation={app.flagAnimation} compact/><div className="profit-overlay"><div className="profit-card-top"><span>ESTIMATED MONTHLY NET PROFIT</span><span className="live-pill"><i/> Live estimate</span></div><div className="profit-value">{money(app.totals?.net)}</div><div className="profit-divider"/><div className="profit-details"><span>{t('revenue')}: {money(app.totals.gross)}</span><span>{t('materials')}: -{money(app.totals.materials)}</span><span>{t('taxReserve')}: -{money(app.totals.tax)}</span></div><div className="country-line"><Flag code={app.country.flag}/><span>{app.country?.name}{app.stateProfile?` • ${app.stateProfile?.name}`:''}</span><span className="rate">{Math.round(app.taxRate*100)}%</span></div></div></section>
 <div className="dashboard-grid"><section className="panel retainer-panel"><div className="panel-head"><div><h2>{t('clientRetainer')}</h2><p>Invite people or attach a recorded service.</p></div><button className="round-btn" onClick={()=>setInvite({})}><Icon name="plus" size={20}/></button></div>{displayClients.length===0?<div className="empty"><Icon name="users" size={25}/><strong>No clients yet</strong><span>Once you add your first client, the sample invite cards disappear.</span><button className="pink-btn" onClick={()=>window.location.href='/clients'}>Add client</button></div>:<div className="client-list">{displayClients.map(c=><div className="client-card" key={c?.id}><div className="client-main"><div className="avatar">{c?.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</div><div><strong>{c?.name}</strong><p>{c?.email||c.phone||'No contact saved'}</p></div></div><div className="client-actions"><button className="ghost-btn" onClick={()=>setQuick(c)}><Icon name="plus" size={15}/>{t('recordService')}</button><button className="pink-btn" onClick={()=>setInvite(c)}><Icon name="send" size={15}/>{t('invite')}</button></div></div>)}</div>}</section>
 <section className="panel summary-panel"><div className="panel-head"><div><h2>{t('thisMonth')}</h2><p>Income and expense pulse.</p></div><Icon name="chart" size={21}/></div><div className="metric-list"><div><span>{t('revenue')}</span><strong>{money(app.totals.gross)}</strong></div><div><span>{t('materials')}</span><strong>-{money(app.totals.materials)}</strong></div><div><span>{t('otherExpenses')}</span><strong>-{money(app.totals.expenses)}</strong></div><div><span>{t('taxReserve')}</span><strong>-{money(app.totals.tax)}</strong></div><div className="metric-total"><span>{t('estimatedNet')}</span><strong>{money(app.totals?.net)}</strong></div></div><div className="summary-note">Tax reserve is calculated as each service is recorded and then aggregated monthly.</div></section></div>
 <TrendChart services={app.services} country={app.country} locale={app.country.locale} taxRate={app.taxRate}/>
 <section className="panel recent-panel"><div className="panel-head"><div><h2>{t('recentWork')}</h2><p>Every recorded item updates your monthly totals.</p></div><a className="text-link" href="/earnings">{t('earnings')} <Icon name="arrow" size={14}/></a></div>{recent.length===0?<div className="empty"><Icon name="spark" size={25}/><strong>No records yet</strong><span>Add your first service or income item and the dashboard will calculate profit, costs and tax reserve.</span></div>:<div className="table-list">{recent.map(x=><div className="table-row" key={x?.id}><div><strong>{x.service}</strong><small>{x.clientName||'Unassigned'} • {new Date(x.date).toLocaleDateString()}</small></div><span>{money(x.amount)}</span><b>{money((Number(x.amount)||0)-(Number(x.materialCost)||0)-(Number(x.extraExpense)||0))}</b></div>)}</div>}</section>
 <section className="referral-offer"><div className="offer-copy"><span className="eyebrow">SOLOPRO REWARD</span><h2>{t('discountTitle')}</h2><p>{app.localizePrices(t('discountIntro'))}</p><small>{ref.count} of 7 new users verified for the next reward.</small></div><div className="offer-action"><span className="old-price">{app.formatUsdPrice(8.99)} / month</span><strong>{app.formatUsdPrice(2.99)}</strong><button className="primary" onClick={()=>setInvite({__referral:true})}>{t('seeHow')}</button><small>{ref.next===7?'Next reward ready to start':'Only '+ref.next+' more new users to go'}</small></div></section>

 <AdBanner />

 <Modal open={countryOpen} onClose={()=>setCountryOpen(false)} title="Quick country switch" wide><p className="modal-sub">Changing country here also switches the default language. You can choose a different language later in Settings.</p><div className="country-select-grid">{COUNTRIES.map(c=><button className={app.countryCode===c.code?'country-option selected':'country-option'} key={c.code} onClick={()=>{app.setCountry(c.code,true);setCountryOpen(false)}}><Flag code={c.flag}/><span>{c?.name}</span>{app.countryCode===c.code&&<Icon name="check" size={16}/>}</button>)}</div></Modal>
 <Modal open={!!quick} onClose={()=>setQuick(null)} title={quick?.name?`${t('recordService')} — ${quick?.name}`:t('recordService')}><form onSubmit={submitQuick} className="form-stack"><label>{t('service')}<input required value={form.service} onChange={e=>setForm({...form,service:e.target?.value})}/></label><label>{t('revenue')}<input required type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target?.value})}/></label><label>{t('materials')}<input type="number" min="0" step="0.01" value={form.materialCost} onChange={e=>setForm({...form,materialCost:e.target?.value})}/></label><label>{t('otherExpenses')}<input type="number" min="0" step="0.01" value={form.extraExpense} onChange={e=>setForm({...form,extraExpense:e.target?.value})}/></label><button className="primary full">{t('save')}</button></form></Modal>
 <InviteModal open={!!invite} onClose={()=>setInvite(null)} clientName={invite?.name||''}/></div>;
}



