import {useMemo,useState} from 'react';
import {useApp,currencyCodeFor} from '../context/AppState';
import Icon from '../components/Icon';
import Modal from '../components/Modal';

export default function Earnings(){
 const app=useApp(); const [open,setOpen]=useState(false); const [templateOpen,setTemplateOpen]=useState(false); const [form,setForm]=useState({service:'',amount:'',materialCost:'',extraExpense:'',clientId:'',recurring:false});
 const money=n=>new Intl.NumberFormat(app.country.locale,{style:'currency',currency:currencyCodeFor(app.country),maximumFractionDigits:2}).format(n||0);
 const list=[...app.services].sort((a,b)=>new Date(b.date)-new Date(a.date));
 const submit=e=>{e.preventDefault();const c=app.clients.find(x=>x?.id===form.clientId);app.addService({...form,clientName:c?.name||'',amount:Number(form.amount)||0,materialCost:Number(form.materialCost)||0,extraExpense:Number(form.extraExpense)||0});if(form.recurring){const templates=JSON.parse(localStorage.getItem('solopro_templates')||'[]');templates.unshift({service:form.service,amount:Number(form.amount)||0,materialCost:Number(form.materialCost)||0,extraExpense:Number(form.extraExpense)||0,clientId:form.clientId,clientName:c?.name||''});localStorage.setItem('solopro_templates',JSON.stringify(templates.slice(0,20)));}setOpen(false);setForm({service:'',amount:'',materialCost:'',extraExpense:'',clientId:'',recurring:false});};
 return <div className="page"><div className="page-top"><div><div className="eyebrow">EARNINGS</div><h1>Money, without the spreadsheet.</h1><p className="sub">Record each income item once. SoloPro immediately reserves estimated tax and calculates your estimated margin.</p></div><button className="primary" onClick={()=>setOpen(true)}><Icon name="plus"/>Add service</button></div>
 <div className="stat-cards"><Stat label="Revenue" value={money(app.totals.gross)}/><Stat label="Direct costs" value={money(app.totals.materials+app.totals.expenses)}/><Stat label="Tax reserve" value={money(app.totals.tax)}/><Stat label="Net profit" value={money(app.totals?.net)} green/></div>
 <div className="panel"><div className="panel-head"><div><h2>Service history</h2><p>{list.length} recorded service{list.length===1?'':'s'}.</p></div><button className="ghost-btn" onClick={()=>setTemplateOpen(true)}><Icon name="clock"/>Saved service templates</button></div>{list.length===0?<div className="empty"><Icon name="dollar" size={25}/><strong>No earnings yet</strong><span>Add a service, or save a fixed service template so repeat bookings take seconds.</span></div>:<div className="table-list">{list.map(x=><div className="table-row detailed" key={x?.id}><div><strong>{x.service}</strong><small>{x.clientName||'Unassigned'} • {new Date(x.date).toLocaleString()}</small></div><span>{money(x.amount)}</span><small>Costs {money((x.materialCost||0)+(x.extraExpense||0))}</small><b>{money((x.amount||0)-(x.materialCost||0)-(x.extraExpense||0))}</b><button className="icon-btn danger" onClick={()=>app.deleteService(x?.id)}><Icon name="trash" size={16}/></button></div>)}</div>}</div>
 <Modal open={open} onClose={()=>setOpen(false)} title="Add a service"><form onSubmit={submit} className="form-stack"><label>Service name<input required value={form.service} onChange={e=>setForm({...form,service:e.target?.value})} placeholder="Service"/></label><label>Attach to client (optional)<select value={form.clientId} onChange={e=>setForm({...form,clientId:e.target?.value})}><option value="">No client / separate income</option>{app.clients.map(c=><option value={c?.id} key={c?.id}>{c?.name}</option>)}</select></label><label>Revenue<input required type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target?.value})} placeholder="85"/></label><div className="two-col"><label>Materials<input type="number" min="0" step="0.01" value={form.materialCost} onChange={e=>setForm({...form,materialCost:e.target?.value})} placeholder="12"/></label><label>Extra expense<input type="number" min="0" step="0.01" value={form.extraExpense} onChange={e=>setForm({...form,extraExpense:e.target?.value})} placeholder="0"/></label></div><label className="check-row template-toggle"><input type="checkbox" checked={form.recurring} onChange={e=>setForm({...form,recurring:e.target.checked})}/> Save as a repeatable service template</label><button className="primary full">Save & calculate</button></form></Modal>
 <Modal open={templateOpen} onClose={()=>setTemplateOpen(false)} title="Fixed service templates"><p className="modal-sub">Save a repeatable income item once, then add it again without retyping the numbers.</p><div className="template-list">{(JSON.parse(localStorage.getItem('solopro_templates')||'[]')).map((t,i)=><div className="template" key={i}><strong>{t.service}</strong><span>{money(t.amount)} • materials {money(t.materialCost)}</span><button className="pink-btn" onClick={()=>{app.addService(t);setTemplateOpen(false)}}>Add</button></div>)}<div className="empty compact"><span>Templates are saved when you tick “Save as a repeatable service template”.</span></div></div></Modal>
 </div>
}
function Stat({label,value,green}){return <div className="stat-card"><span>{label}</span><strong className={green?'green':''}>{value}</strong></div>}



