import { useMemo, useState } from 'react';
import { useApp, currencyCodeFor } from '../context/AppState';
import Icon from '../components/Icon';
import Modal from '../components/Modal';
import InviteModal from '../components/InviteModal';

const EARNINGS_COPY={
  English:{"eyebrow":"EARNINGS","invite":"Invite","addService":"Add service","taxReserve":"Tax reserve","taxOn":"SoloPro keeps an estimated tax amount aside.","taxOff":"No automatic tax is deducted from your income.","income":"Income","expense":"Expenses","netAvailable":"Net available","additionalIncome":"Additional income","additionalExpenses":"Additional expenses","addIncome":"Add income","addExpense":"Add expense","serviceHistory":"Service history","savedTemplates":"Saved service templates","noServices":"No services yet","service":"Service","add":"Add","edit":"Edit","incomeQuestion":"What is this income?","expenseQuestion":"What is this expense for?","amount":"Amount","date":"Date","serviceName":"Service name","attachClient":"Attach to client (optional)","noClient":"No client / separate income","revenue":"Revenue","materials":"Materials","extraExpense":"Extra expense","saveTemplate":"Save as a repeatable service template","saveService":"Save service","repeatableIncome":"Save a repeatable income item once, then add it again without retyping the numbers.","templatesSaved":"Templates are saved when you tick “Save as a repeatable service template”."},
  Italian:{"eyebrow":"ENTRATE","invite":"Invita","addService":"Aggiungi servizio","taxReserve":"Riserva fiscale","taxOn":"SoloPro mette da parte un importo fiscale stimato.","taxOff":"Nessuna imposta viene detratta automaticamente dalle tue entrate.","income":"Entrate","expense":"Spese","netAvailable":"Netto disponibile","additionalIncome":"Entrate aggiuntive","additionalExpenses":"Spese aggiuntive","addIncome":"Aggiungi entrata","addExpense":"Aggiungi spesa","serviceHistory":"Storico servizi","savedTemplates":"Modelli di servizio salvati","noServices":"Nessun servizio ancora","service":"Servizio","add":"Aggiungi","edit":"Modifica","incomeQuestion":"A cosa si riferisce questa entrata?","expenseQuestion":"Per cosa è questa spesa?","amount":"Importo","date":"Data","serviceName":"Nome del servizio","attachClient":"Collega al cliente (opzionale)","noClient":"Nessun cliente / entrata separata","revenue":"Ricavi","materials":"Materiali","extraExpense":"Spesa extra","saveTemplate":"Salva come modello di servizio riutilizzabile","saveService":"Salva servizio","repeatableIncome":"Salva una voce di entrata riutilizzabile una volta, poi aggiungila di nuovo senza riscrivere i numeri.","templatesSaved":"I modelli vengono salvati quando selezioni “Salva come modello di servizio riutilizzabile”."},
  French:{"eyebrow":"REVENUS","invite":"Inviter","addService":"Ajouter un service","taxReserve":"Réserve fiscale","taxOn":"SoloPro met de côté un montant fiscal estimé.","taxOff":"Aucun impôt n’est déduit automatiquement de vos revenus.","income":"Revenu","expense":"Dépenses","netAvailable":"Net disponible","additionalIncome":"Revenus supplémentaires","additionalExpenses":"Dépenses supplémentaires","addIncome":"Ajouter un revenu","addExpense":"Ajouter une dépense","serviceHistory":"Historique des services","savedTemplates":"Modèles de services enregistrés","noServices":"Aucun service pour le moment","service":"Service","add":"Ajouter","edit":"Modifier","incomeQuestion":"À quoi correspond ce revenu ?","expenseQuestion":"À quoi correspond cette dépense ?","amount":"Montant","date":"Date","serviceName":"Nom du service","attachClient":"Associer à un client (facultatif)","noClient":"Aucun client / revenu séparé","revenue":"Chiffre d’affaires","materials":"Matériaux","extraExpense":"Dépense supplémentaire","saveTemplate":"Enregistrer comme modèle de service réutilisable","saveService":"Enregistrer le service","repeatableIncome":"Enregistrez une entrée de revenu réutilisable une fois, puis ajoutez-la sans ressaisir les chiffres.","templatesSaved":"Les modèles sont enregistrés lorsque vous cochez « Enregistrer comme modèle de service réutilisable »."},
  German:{"eyebrow":"EINNAHMEN","invite":"Einladen","addService":"Leistung hinzufügen","taxReserve":"Steuerrücklage","taxOn":"SoloPro legt einen geschätzten Steuerbetrag zurück.","taxOff":"Von deinen Einnahmen wird keine Steuer automatisch abgezogen.","income":"Einnahmen","expense":"Ausgaben","netAvailable":"Verfügbar netto","additionalIncome":"Zusätzliche Einnahmen","additionalExpenses":"Zusätzliche Ausgaben","addIncome":"Einnahme hinzufügen","addExpense":"Ausgabe hinzufügen","serviceHistory":"Leistungshistorie","savedTemplates":"Gespeicherte Leistungsvorlagen","noServices":"Noch keine Leistungen","service":"Leistung","add":"Hinzufügen","edit":"Bearbeiten","incomeQuestion":"Wofür ist diese Einnahme?","expenseQuestion":"Wofür ist diese Ausgabe?","amount":"Betrag","date":"Datum","serviceName":"Leistungsname","attachClient":"Kunde zuordnen (optional)","noClient":"Kein Kunde / separate Einnahme","revenue":"Umsatz","materials":"Materialien","extraExpense":"Zusätzliche Ausgabe","saveTemplate":"Als wiederverwendbare Leistungsvorlage speichern","saveService":"Leistung speichern","repeatableIncome":"Speichere eine wiederverwendbare Einnahme einmal und füge sie später ohne erneute Eingabe hinzu.","templatesSaved":"Vorlagen werden gespeichert, wenn du „Als wiederverwendbare Leistungsvorlage speichern“ auswählst."},
  Spanish:{"eyebrow":"INGRESOS","invite":"Invitar","addService":"Añadir servicio","taxReserve":"Reserva fiscal","taxOn":"SoloPro reserva un importe de impuestos estimado.","taxOff":"No se descuenta ningún impuesto automáticamente de tus ingresos.","income":"Ingresos","expense":"Gastos","netAvailable":"Neto disponible","additionalIncome":"Ingresos adicionales","additionalExpenses":"Gastos adicionales","addIncome":"Añadir ingreso","addExpense":"Añadir gasto","serviceHistory":"Historial de servicios","savedTemplates":"Plantillas de servicios guardadas","noServices":"Aún no hay servicios","service":"Servicio","add":"Añadir","edit":"Editar","incomeQuestion":"¿De qué es este ingreso?","expenseQuestion":"¿Para qué es este gasto?","amount":"Importe","date":"Fecha","serviceName":"Nombre del servicio","attachClient":"Vincular al cliente (opcional)","noClient":"Sin cliente / ingreso separado","revenue":"Ingresos","materials":"Materiales","extraExpense":"Gasto extra","saveTemplate":"Guardar como plantilla de servicio reutilizable","saveService":"Guardar servicio","repeatableIncome":"Guarda una entrada de ingreso reutilizable una vez y vuelve a añadirla sin escribir los números otra vez.","templatesSaved":"Las plantillas se guardan cuando marcas «Guardar como plantilla de servicio reutilizable»."},
  Polish:{"eyebrow":"PRZYCHODY","invite":"Zaproś","addService":"Dodaj usługę","taxReserve":"Rezerwa podatkowa","taxOn":"SoloPro odkłada szacowaną kwotę podatku.","taxOff":"Z Twoich przychodów nie jest automatycznie potrącany podatek.","income":"Przychód","expense":"Wydatki","netAvailable":"Dostępne netto","additionalIncome":"Dodatkowe przychody","additionalExpenses":"Dodatkowe wydatki","addIncome":"Dodaj przychód","addExpense":"Dodaj wydatek","serviceHistory":"Historia usług","savedTemplates":"Zapisane szablony usług","noServices":"Brak usług","service":"Usługa","add":"Dodaj","edit":"Edytuj","incomeQuestion":"Czego dotyczy ten przychód?","expenseQuestion":"Czego dotyczy ten wydatek?","amount":"Kwota","date":"Data","serviceName":"Nazwa usługi","attachClient":"Przypisz do klienta (opcjonalnie)","noClient":"Brak klienta / osobny przychód","revenue":"Przychód","materials":"Materiały","extraExpense":"Dodatkowy wydatek","saveTemplate":"Zapisz jako szablon wielokrotnego użycia","saveService":"Zapisz usługę","repeatableIncome":"Zapisz powtarzalną pozycję przychodu raz, a potem dodawaj ją bez ponownego wpisywania liczb.","templatesSaved":"Szablony są zapisywane po zaznaczeniu „Zapisz jako szablon wielokrotnego użycia”."},
  Japanese:{"eyebrow":"収入","invite":"招待","addService":"サービスを追加","taxReserve":"税金準備額","taxOn":"SoloProは推定税額を確保します。","taxOff":"収入から税金が自動的に差し引かれることはありません。","income":"収入","expense":"支出","netAvailable":"利用可能な純額","additionalIncome":"追加収入","additionalExpenses":"追加支出","addIncome":"収入を追加","addExpense":"支出を追加","serviceHistory":"サービス履歴","savedTemplates":"保存したサービステンプレート","noServices":"サービスはまだありません","service":"サービス","add":"追加","edit":"編集","incomeQuestion":"この収入の内容は？","expenseQuestion":"この支出の内容は？","amount":"金額","date":"日付","serviceName":"サービス名","attachClient":"顧客に紐付け（任意）","noClient":"顧客なし / 別収入","revenue":"売上","materials":"材料費","extraExpense":"追加費用","saveTemplate":"繰り返し使うサービステンプレートとして保存","saveService":"サービスを保存","repeatableIncome":"繰り返し使う収入項目を一度保存すれば、数字を再入力せずに追加できます。","templatesSaved":"「繰り返し使うサービステンプレートとして保存」を選択するとテンプレートが保存されます。"},
  Korean:{"eyebrow":"수입","invite":"초대","addService":"서비스 추가","taxReserve":"세금 적립금","taxOn":"SoloPro가 예상 세금을 따로 적립합니다.","taxOff":"수입에서 세금이 자동으로 공제되지 않습니다.","income":"수입","expense":"지출","netAvailable":"사용 가능 순액","additionalIncome":"추가 수입","additionalExpenses":"추가 지출","addIncome":"수입 추가","addExpense":"지출 추가","serviceHistory":"서비스 기록","savedTemplates":"저장된 서비스 템플릿","noServices":"아직 서비스가 없습니다","service":"서비스","add":"추가","edit":"수정","incomeQuestion":"이 수입은 무엇인가요?","expenseQuestion":"이 지출은 무엇을 위한 것인가요?","amount":"금액","date":"날짜","serviceName":"서비스 이름","attachClient":"고객 연결 (선택 사항)","noClient":"고객 없음 / 별도 수입","revenue":"매출","materials":"재료비","extraExpense":"추가 지출","saveTemplate":"반복 서비스 템플릿으로 저장","saveService":"서비스 저장","repeatableIncome":"반복해서 사용할 수입 항목을 한 번 저장하면 숫자를 다시 입력하지 않고 추가할 수 있습니다.","templatesSaved":"“반복 서비스 템플릿으로 저장”을 선택하면 템플릿이 저장됩니다."},
  Ukrainian:{"eyebrow":"ДОХОДИ","invite":"Запросити","addService":"Додати послугу","taxReserve":"Податковий резерв","taxOn":"SoloPro відкладає орієнтовну суму податку.","taxOff":"З ваших доходів автоматично не відраховується податок.","income":"Дохід","expense":"Витрати","netAvailable":"Доступно після витрат","additionalIncome":"Додаткові доходи","additionalExpenses":"Додаткові витрати","addIncome":"Додати дохід","addExpense":"Додати витрату","serviceHistory":"Історія послуг","savedTemplates":"Збережені шаблони послуг","noServices":"Послуг ще немає","service":"Послуга","add":"Додати","edit":"Редагувати","incomeQuestion":"Що це за дохід?","expenseQuestion":"На що ця витрата?","amount":"Сума","date":"Дата","serviceName":"Назва послуги","attachClient":"Прив’язати до клієнта (необов’язково)","noClient":"Без клієнта / окремий дохід","revenue":"Дохід","materials":"Матеріали","extraExpense":"Додаткова витрата","saveTemplate":"Зберегти як багаторазовий шаблон послуги","saveService":"Зберегти послугу","repeatableIncome":"Збережіть повторювану статтю доходу один раз, а потім додавайте її без повторного введення цифр.","templatesSaved":"Шаблони зберігаються, коли ви позначаєте «Зберегти як багаторазовий шаблон послуги»."},
  Portuguese:{"eyebrow":"RENDIMENTOS","invite":"Convidar","addService":"Adicionar serviço","taxReserve":"Reserva fiscal","taxOn":"O SoloPro reserva um valor estimado para impostos.","taxOff":"Nenhum imposto é deduzido automaticamente dos seus rendimentos.","income":"Rendimento","expense":"Despesas","netAvailable":"Líquido disponível","additionalIncome":"Rendimento adicional","additionalExpenses":"Despesas adicionais","addIncome":"Adicionar rendimento","addExpense":"Adicionar despesa","serviceHistory":"Histórico de serviços","savedTemplates":"Modelos de serviço guardados","noServices":"Ainda não há serviços","service":"Serviço","add":"Adicionar","edit":"Editar","incomeQuestion":"A que se refere este rendimento?","expenseQuestion":"Para que serve esta despesa?","amount":"Valor","date":"Data","serviceName":"Nome do serviço","attachClient":"Associar ao cliente (opcional)","noClient":"Sem cliente / rendimento separado","revenue":"Receita","materials":"Materiais","extraExpense":"Despesa extra","saveTemplate":"Guardar como modelo de serviço reutilizável","saveService":"Guardar serviço","repeatableIncome":"Guarde um item de rendimento reutilizável uma vez e volte a adicioná-lo sem reintroduzir os números.","templatesSaved":"Os modelos são guardados quando seleciona «Guardar como modelo de serviço reutilizável»."},
  Dutch:{"eyebrow":"INKOMSTEN","invite":"Uitnodigen","addService":"Dienst toevoegen","taxReserve":"Belastingreserve","taxOn":"SoloPro zet een geschat belastingbedrag opzij.","taxOff":"Er wordt geen belasting automatisch van je inkomsten afgetrokken.","income":"Inkomsten","expense":"Uitgaven","netAvailable":"Netto beschikbaar","additionalIncome":"Extra inkomsten","additionalExpenses":"Extra uitgaven","addIncome":"Inkomsten toevoegen","addExpense":"Uitgave toevoegen","serviceHistory":"Dienstgeschiedenis","savedTemplates":"Opgeslagen dienstsjablonen","noServices":"Nog geen diensten","service":"Dienst","add":"Toevoegen","edit":"Bewerken","incomeQuestion":"Waar gaat deze inkomstenpost over?","expenseQuestion":"Waarvoor is deze uitgave?","amount":"Bedrag","date":"Datum","serviceName":"Naam van dienst","attachClient":"Aan klant koppelen (optioneel)","noClient":"Geen klant / aparte inkomsten","revenue":"Omzet","materials":"Materialen","extraExpense":"Extra uitgave","saveTemplate":"Opslaan als herbruikbaar dienstsjabloon","saveService":"Dienst opslaan","repeatableIncome":"Sla een herbruikbaar inkomstenitem één keer op en voeg het later toe zonder de cijfers opnieuw in te voeren.","templatesSaved":"Sjablonen worden opgeslagen wanneer je “Opslaan als herbruikbaar dienstsjabloon” aanvinkt."},
  Czech:{"eyebrow":"PŘÍJMY","invite":"Pozvat","addService":"Přidat službu","taxReserve":"Daňová rezerva","taxOn":"SoloPro odkládá odhadovanou částku daně.","taxOff":"Z příjmu se automaticky neodečítá žádná daň.","income":"Příjem","expense":"Výdaje","netAvailable":"Čistá částka","additionalIncome":"Další příjmy","additionalExpenses":"Další výdaje","addIncome":"Přidat příjem","addExpense":"Přidat výdaj","serviceHistory":"Historie služeb","savedTemplates":"Uložené šablony služeb","noServices":"Zatím žádné služby","service":"Služba","add":"Přidat","edit":"Upravit","incomeQuestion":"Čeho se tento příjem týká?","expenseQuestion":"K čemu je tento výdaj?","amount":"Částka","date":"Datum","serviceName":"Název služby","attachClient":"Přiřadit klientovi (volitelné)","noClient":"Bez klienta / samostatný příjem","revenue":"Tržby","materials":"Materiály","extraExpense":"Další výdaj","saveTemplate":"Uložit jako opakovaně použitelnou šablonu služby","saveService":"Uložit službu","repeatableIncome":"Uložte opakovaně používanou položku příjmu jednou a potom ji přidávejte bez opětovného zadávání čísel.","templatesSaved":"Šablony se uloží, když zaškrtnete „Uložit jako opakovaně použitelnou šablonu služby“."},
  Finnish:{"eyebrow":"TULOT","invite":"Kutsu","addService":"Lisää palvelu","taxReserve":"Verovaraus","taxOn":"SoloPro varaa arvioidun veron määrän.","taxOff":"Tuloistasi ei vähennetä veroja automaattisesti.","income":"Tulo","expense":"Menot","netAvailable":"Käytettävissä","additionalIncome":"Muut tulot","additionalExpenses":"Muut menot","addIncome":"Lisää tulo","addExpense":"Lisää meno","serviceHistory":"Palveluhistoria","savedTemplates":"Tallennetut palvelumallit","noServices":"Ei vielä palveluita","service":"Palvelu","add":"Lisää","edit":"Muokkaa","incomeQuestion":"Mihin tämä tulo liittyy?","expenseQuestion":"Mihin tämä meno liittyy?","amount":"Summa","date":"Päivä","serviceName":"Palvelun nimi","attachClient":"Liitä asiakkaaseen (valinnainen)","noClient":"Ei asiakasta / erillinen tulo","revenue":"Liikevaihto","materials":"Materiaalit","extraExpense":"Lisäkulu","saveTemplate":"Tallenna uudelleenkäytettäväksi palvelumalliksi","saveService":"Tallenna palvelu","repeatableIncome":"Tallenna toistuva tulo kerran ja lisää se myöhemmin syöttämättä numeroita uudelleen.","templatesSaved":"Mallit tallennetaan, kun valitset ”Tallenna uudelleenkäytettäväksi palvelumalliksi”."},
  Swedish:{"eyebrow":"INTÄKTER","invite":"Bjud in","addService":"Lägg till tjänst","taxReserve":"Skattereserv","taxOn":"SoloPro avsätter ett uppskattat skattebelopp.","taxOff":"Ingen skatt dras automatiskt från dina inkomster.","income":"Inkomst","expense":"Utgifter","netAvailable":"Netto tillgängligt","additionalIncome":"Övriga inkomster","additionalExpenses":"Övriga utgifter","addIncome":"Lägg till inkomst","addExpense":"Lägg till utgift","serviceHistory":"Tjänstehistorik","savedTemplates":"Sparade tjänstemallar","noServices":"Inga tjänster ännu","service":"Tjänst","add":"Lägg till","edit":"Redigera","incomeQuestion":"Vad gäller den här inkomsten?","expenseQuestion":"Vad gäller den här utgiften?","amount":"Belopp","date":"Datum","serviceName":"Tjänstens namn","attachClient":"Koppla till kund (valfritt)","noClient":"Ingen kund / separat inkomst","revenue":"Intäkt","materials":"Material","extraExpense":"Extra utgift","saveTemplate":"Spara som återanvändbar tjänstemall","saveService":"Spara tjänst","repeatableIncome":"Spara en återanvändbar inkomstpost en gång och lägg till den igen utan att skriva in siffrorna på nytt.","templatesSaved":"Mallar sparas när du markerar ”Spara som återanvändbar tjänstemall”."},
  Danish:{"eyebrow":"INDTÆGTER","invite":"Inviter","addService":"Tilføj service","taxReserve":"Skattereserve","taxOn":"SoloPro afsætter et estimeret skattebeløb.","taxOff":"Der trækkes ikke automatisk skat fra din indkomst.","income":"Indtægt","expense":"Udgifter","netAvailable":"Netto tilgængeligt","additionalIncome":"Ekstra indtægt","additionalExpenses":"Ekstra udgifter","addIncome":"Tilføj indtægt","addExpense":"Tilføj udgift","serviceHistory":"Servicehistorik","savedTemplates":"Gemte serviceskabeloner","noServices":"Ingen services endnu","service":"Service","add":"Tilføj","edit":"Rediger","incomeQuestion":"Hvad er denne indtægt?","expenseQuestion":"Hvad er denne udgift til?","amount":"Beløb","date":"Dato","serviceName":"Servicenavn","attachClient":"Tilknyt kunde (valgfrit)","noClient":"Ingen kunde / separat indtægt","revenue":"Omsætning","materials":"Materialer","extraExpense":"Ekstra udgift","saveTemplate":"Gem som genanvendelig serviceskabelon","saveService":"Gem service","repeatableIncome":"Gem en genanvendelig indtægt én gang, og tilføj den igen uden at indtaste tallene på ny.","templatesSaved":"Skabeloner gemmes, når du markerer “Gem som genanvendelig serviceskabelon”."},
  Norwegian:{"eyebrow":"INNTEKTER","invite":"Inviter","addService":"Legg til tjeneste","taxReserve":"Skattereserve","taxOn":"SoloPro setter av et estimert skattebeløp.","taxOff":"Det trekkes ikke automatisk skatt fra inntekten din.","income":"Inntekt","expense":"Utgifter","netAvailable":"Netto tilgjengelig","additionalIncome":"Andre inntekter","additionalExpenses":"Andre utgifter","addIncome":"Legg til inntekt","addExpense":"Legg til utgift","serviceHistory":"Tjenestehistorikk","savedTemplates":"Lagrede tjenestemaler","noServices":"Ingen tjenester ennå","service":"Tjeneste","add":"Legg til","edit":"Rediger","incomeQuestion":"Hva gjelder denne inntekten?","expenseQuestion":"Hva gjelder denne utgiften?","amount":"Beløp","date":"Dato","serviceName":"Tjenestenavn","attachClient":"Knytt til kunde (valgfritt)","noClient":"Ingen kunde / separat inntekt","revenue":"Inntekt","materials":"Materialer","extraExpense":"Ekstra utgift","saveTemplate":"Lagre som gjenbrukbar tjenestemal","saveService":"Lagre tjeneste","repeatableIncome":"Lagre en gjenbrukbar inntekt én gang, og legg den til igjen uten å skrive inn tallene på nytt.","templatesSaved":"Maler lagres når du krysser av for «Lagre som gjenbrukbar tjenestemal»."},
  Icelandic:{"eyebrow":"TEKJUR","invite":"Bjóða","addService":"Bæta við þjónustu","taxReserve":"Skattforði","taxOn":"SoloPro leggur til hliðar áætlaða skattupphæð.","taxOff":"Enginn skattur er dreginn sjálfkrafa frá tekjum þínum.","income":"Tekjur","expense":"Gjöld","netAvailable":"Hreint til ráðstöfunar","additionalIncome":"Aðrar tekjur","additionalExpenses":"Önnur gjöld","addIncome":"Bæta við tekjum","addExpense":"Bæta við gjaldi","serviceHistory":"Þjónustusaga","savedTemplates":"Vistað þjónustusnið","noServices":"Engin þjónusta enn","service":"Þjónusta","add":"Bæta við","edit":"Breyta","incomeQuestion":"Hvað eru þessar tekjur?","expenseQuestion":"Hvað er þetta gjald fyrir?","amount":"Upphæð","date":"Dagsetning","serviceName":"Nafn þjónustu","attachClient":"Tengja við viðskiptavin (valfrjálst)","noClient":"Enginn viðskiptavinur / aðrar tekjur","revenue":"Tekjur","materials":"Efni","extraExpense":"Aukakostnaður","saveTemplate":"Vista sem endurnýtanlegt þjónustusnið","saveService":"Vista þjónustu","repeatableIncome":"Vistaðu endurnýtanlega tekjuliði einu sinni og bættu þeim síðan við án þess að slá tölurnar inn aftur.","templatesSaved":"Snið eru vistuð þegar þú velur „Vista sem endurnýtanlegt þjónustusnið“."},
  Arabic:{"eyebrow":"الإيرادات","invite":"دعوة","addService":"إضافة خدمة","taxReserve":"احتياطي الضريبة","taxOn":"يحتفظ SoloPro بمبلغ ضريبي تقديري جانبًا.","taxOff":"لا يتم خصم أي ضريبة تلقائيًا من دخلك.","income":"الدخل","expense":"المصروفات","netAvailable":"الصافي المتاح","additionalIncome":"دخل إضافي","additionalExpenses":"مصروفات إضافية","addIncome":"إضافة دخل","addExpense":"إضافة مصروف","serviceHistory":"سجل الخدمات","savedTemplates":"قوالب الخدمات المحفوظة","noServices":"لا توجد خدمات بعد","service":"الخدمة","add":"إضافة","edit":"تعديل","incomeQuestion":"ما هذا الدخل؟","expenseQuestion":"ما الغرض من هذا المصروف؟","amount":"المبلغ","date":"التاريخ","serviceName":"اسم الخدمة","attachClient":"ربط بالعميل (اختياري)","noClient":"بدون عميل / دخل منفصل","revenue":"الإيرادات","materials":"المواد","extraExpense":"مصروف إضافي","saveTemplate":"حفظ كقالب خدمة قابل لإعادة الاستخدام","saveService":"حفظ الخدمة","repeatableIncome":"احفظ عنصر دخل قابلًا لإعادة الاستخدام مرة واحدة، ثم أضفه مجددًا دون إعادة إدخال الأرقام.","templatesSaved":"يتم حفظ القوالب عند تحديد «حفظ كقالب خدمة قابل لإعادة الاستخدام»."},
  Chinese:{"eyebrow":"收入","invite":"邀请","addService":"添加服务","taxReserve":"税务储备","taxOn":"SoloPro 会预留预计税款。","taxOff":"不会自动从你的收入中扣除税款。","income":"收入","expense":"支出","netAvailable":"可用净额","additionalIncome":"额外收入","additionalExpenses":"额外支出","addIncome":"添加收入","addExpense":"添加支出","serviceHistory":"服务记录","savedTemplates":"已保存的服务模板","noServices":"暂无服务","service":"服务","add":"添加","edit":"编辑","incomeQuestion":"这笔收入是什么？","expenseQuestion":"这笔支出用于什么？","amount":"金额","date":"日期","serviceName":"服务名称","attachClient":"关联客户（可选）","noClient":"无客户 / 单独收入","revenue":"收入","materials":"材料","extraExpense":"额外支出","saveTemplate":"保存为可重复使用的服务模板","saveService":"保存服务","repeatableIncome":"保存一次可重复使用的收入项目，以后无需重新输入数字即可再次添加。","templatesSaved":"勾选“保存为可重复使用的服务模板”后，模板会被保存。"}
};
const emptyService={service:'',amount:'',materialCost:'',extraExpense:'',clientId:'',recurring:false};
const emptyEntry={label:'',amount:'',date:new Date().toISOString().slice(0,10)};

export default function Earnings(){
 const app=useApp();
 const copy=EARNINGS_COPY[app.language]||EARNINGS_COPY.English;
 const [open,setOpen]=useState(false);
 const [inviteOpen,setInviteOpen]=useState(false);
 const [templateOpen,setTemplateOpen]=useState(false);
 const [entryOpen,setEntryOpen]=useState(false);
 const [editing,setEditing]=useState(null);
 const [form,setForm]=useState(emptyService);
 const [entry,setEntry]=useState(emptyEntry);
 const [entryType,setEntryType]=useState('income');
 const money=n=>new Intl.NumberFormat(app.country.locale,{style:'currency',currency:currencyCodeFor(app.country),maximumFractionDigits:2}).format(n||0);
 const services=[...app.services].sort((a,b)=>new Date(b.date)-new Date(a.date));
 const customIncome=Array.isArray(app.financialIncome)?app.financialIncome:[];
 const customExpenses=Array.isArray(app.financialExpenses)?app.financialExpenses:[];
 const now=new Date();
 const inMonth=x=>{const d=new Date(x.date);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear();};
 const monthIncome=customIncome.filter(inMonth);
 const monthExpenses=customExpenses.filter(inMonth);
 const serviceRevenue=app.monthlyServices.reduce((s,x)=>s+Number(x.amount||0),0);
 const serviceMaterials=app.monthlyServices.reduce((s,x)=>s+Number(x.materialCost||0),0);
 const serviceExtra=app.monthlyServices.reduce((s,x)=>s+Number(x.extraExpense||0),0);
 const fixedMonthly=app.fixedExpensePeriod==='weekly'?Number(app.fixedExpenses||0)*52/12:Number(app.fixedExpenses||0);
 const revenue=serviceRevenue+monthIncome.reduce((s,x)=>s+Number(x.amount||0),0);
 const variableExpenses=serviceMaterials+serviceExtra+monthExpenses.reduce((s,x)=>s+Number(x.amount||0),0);
 const expenses=variableExpenses+fixedMonthly;
 const tax=app.taxMode==='reserve'?Math.max(0,revenue-variableExpenses)*Number(app.taxRate||0):0;
 const net=revenue-expenses-tax;
 const submitService=e=>{e.preventDefault();const c=app.clients.find(x=>x.id===form.clientId);app.addService({...form,clientName:c?.name||'',amount:Number(form.amount)||0,materialCost:Number(form.materialCost)||0,extraExpense:Number(form.extraExpense)||0});if(form.recurring){const templates=JSON.parse(localStorage.getItem('solopro_templates')||'[]');templates.unshift({service:form.service,amount:Number(form.amount)||0,materialCost:Number(form.materialCost)||0,extraExpense:Number(form.extraExpense)||0,clientId:form.clientId,clientName:c?.name||''});localStorage.setItem('solopro_templates',JSON.stringify(templates.slice(0,20)));}setOpen(false);setForm(emptyService);};
 const openEntry=(type,item=null)=>{setEntryType(type);setEditing(item?.id||null);setEntry(item?{label:item.label||'',amount:String(item.amount??''),date:String(item.date||'').slice(0,10)||emptyEntry.date}:emptyEntry);setEntryOpen(true);};
 const saveEntry=e=>{e.preventDefault();const item={id:editing||crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`,label:entry.label.trim(),amount:Math.abs(Number(entry.amount)||0),date:entry.date||emptyEntry.date};if(!item.label)return;const key=entryType==='income'?'financialIncome':'financialExpenses';const current=Array.isArray(app[key])?app[key]:[];app.update({[key]:editing?current.map(x=>x.id===editing?item:x):[...current,item]});setEntryOpen(false);setEditing(null);setEntry(emptyEntry);};
 const deleteEntry=(type,id)=>{const key=type==='income'?'financialIncome':'financialExpenses';const current=Array.isArray(app[key])?app[key]:[];app.update({[key]:current.filter(x=>x.id!==id)});};
 return <div className="page">
  <div className="page-top">
   <div><div className="eyebrow">{copy.eyebrow}</div><h1>{copy.title}</h1><p className="sub">{copy.subtitle}</p></div>
   <div className="page-actions"><button className="ghost-btn" onClick={()=>setInviteOpen(true)}><Icon name="send"/>{copy.invite}</button><button className="primary" onClick={()=>setOpen(true)}><Icon name="plus"/>{copy.addService}</button></div>
  </div>

  <div className="panel" style={{marginBottom:18}}>
   <div className="panel-head"><div><h2>{copy.taxReserve}</h2><p>{app.taxMode==='reserve'?copy.taxOn:copy.taxOff}</p></div><button className={app.taxMode==='reserve'?'primary':'ghost-btn'} onClick={()=>app.update({taxMode:app.taxMode==='reserve'?'off':'reserve'})}>{app.taxMode==='reserve'?'ON':'OFF'}</button></div>
   <small>{copy.taxHint}</small>
  </div>

  <div className="stat-cards">
   <Stat label={copy.income} value={money(revenue)}/><Stat label={copy.expense} value={money(expenses)}/><Stat label={copy.taxReserve} value={money(tax)}/><Stat label="Net available" value={money(net)} green/>
  </div>

  <div className="dashboard-grid" style={{marginBottom:18}}>
   <section className="panel"><div className="panel-head"><div><h2>{copy.additionalIncome}</h2><p>{copy.incomeDesc}</p></div><button className="round-btn" onClick={()=>openEntry('income')}><Icon name="plus" size={20}/></button></div>
    {monthIncome.length===0?<div className="empty compact"><span>{copy.noIncome}</span><button className="pink-btn" onClick={()=>openEntry('income')}>{copy.addIncome}</button></div>:<div className="table-list">{monthIncome.map(x=><div className="table-row detailed" key={x.id}><div><strong>{x.label}</strong><small>{new Date(x.date).toLocaleDateString()}</small></div><span>{money(x.amount)}</span><button className="icon-btn" onClick={()=>openEntry('income',x)}><Icon name="edit" size={15}/></button><button className="icon-btn danger" onClick={()=>deleteEntry('income',x.id)}><Icon name="trash" size={15}/></button></div>)}</div>}
   </section>
   <section className="panel"><div className="panel-head"><div><h2>{copy.additionalExpenses}</h2><p>{copy.expenseDesc}</p></div><button className="round-btn" onClick={()=>openEntry('expense')}><Icon name="plus" size={20}/></button></div>
    {monthExpenses.length===0?<div className="empty compact"><span>{copy.noExpense}</span><button className="pink-btn" onClick={()=>openEntry('expense')}>{copy.addExpense}</button></div>:<div className="table-list">{monthExpenses.map(x=><div className="table-row detailed" key={x.id}><div><strong>{x.label}</strong><small>{new Date(x.date).toLocaleDateString()}</small></div><span>-{money(x.amount)}</span><button className="icon-btn" onClick={()=>openEntry('expense',x)}><Icon name="edit" size={15}/></button><button className="icon-btn danger" onClick={()=>deleteEntry('expense',x.id)}><Icon name="trash" size={15}/></button></div>)}</div>}
   </section>
  </div>

  <div className="panel">
   <div className="panel-head"><div><h2>{copy.serviceHistory}</h2><p>{services.length} recorded service{services.length===1?'':'s'}.</p></div><button className="ghost-btn" onClick={()=>setTemplateOpen(true)}><Icon name="clock"/>{copy.savedTemplates}</button></div>
   {services.length===0?<div className="empty"><Icon name="dollar" size={25}/><strong>{copy.noServices}</strong><span>{copy.noServicesDesc}</span></div>:<div className="table-list">{services.map(x=><div className="table-row detailed" key={x.id}><div><strong>{x.service}</strong><small>{x.clientName||'Unassigned'} — {new Date(x.date).toLocaleString()}</small></div><span>{money(x.amount)}</span><small>Costs {money((x.materialCost||0)+(x.extraExpense||0))}</small><b>{money((x.amount||0)-(x.materialCost||0)-(x.extraExpense||0))}</b><button className="icon-btn danger" onClick={()=>app.deleteService(x.id)}><Icon name="trash" size={16}/></button></div>)}</div>}
  </div>

  <InviteModal open={inviteOpen} onClose={()=>setInviteOpen(false)}/>
  <Modal open={entryOpen} onClose={()=>setEntryOpen(false)} title={`${editing?copy.edit:copy.add} ${entryType==='income'?'income':'expense'}`}>
   <form onSubmit={saveEntry} className="form-stack"><label>{entryType==='income'?'What is this income?':'What is this expense for?'}<input required value={entry.label} onChange={e=>setEntry({...entry,label:e.target.value})} placeholder={entryType==='income'?'Part-time job':'Car insurance'}/></label><label>{copy.amount}<input required type="number" min="0" step="0.01" value={entry.amount} onChange={e=>setEntry({...entry,amount:e.target.value})} placeholder="100"/></label><label>{copy.date}<input required type="date" value={entry.date} onChange={e=>setEntry({...entry,date:e.target.value})}/></label><button className="primary full">{editing?copy.saveService:copy.add}</button></form>
  </Modal>
  <Modal open={open} onClose={()=>setOpen(false)} title={copy.addService}>
   <form onSubmit={submitService} className="form-stack"><label>{copy.serviceName}<input required value={form.service} onChange={e=>setForm({...form,service:e.target.value})} placeholder="Service"/></label><label>{copy.attachClient}<select value={form.clientId} onChange={e=>setForm({...form,clientId:e.target.value})}><option value="">{copy.noClient}</option>{app.clients.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>{copy.revenue}<input required type="number" min="0" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})} placeholder="85"/></label><div className="two-col"><label>{copy.materials}<input type="number" min="0" step="0.01" value={form.materialCost} onChange={e=>setForm({...form,materialCost:e.target.value})} placeholder="12"/></label><label>{copy.extraExpense}<input type="number" min="0" step="0.01" value={form.extraExpense} onChange={e=>setForm({...form,extraExpense:e.target.value})} placeholder="0"/></label></div><label className="check-row template-toggle"><input type="checkbox" checked={form.recurring} onChange={e=>setForm({...form,recurring:e.target.checked})}/> {copy.saveTemplate}</label><button className="primary full">{copy.saveService}</button></form>
  </Modal>
  <Modal open={templateOpen} onClose={()=>setTemplateOpen(false)} title={copy.savedTemplates}><p className="modal-sub">{copy.repeatableIncome}</p><div className="template-list">{(JSON.parse(localStorage.getItem('solopro_templates')||'[]')).map((t,i)=><div className="template" key={i}><strong>{t.service}</strong><span>{money(t.amount)} — materials {money(t.materialCost)}</span><button className="pink-btn" onClick={()=>{app.addService(t);setTemplateOpen(false)}}>{copy.add}</button></div>)}<div className="empty compact"><span>{copy.templatesSaved}</span></div></div></Modal>
 </div>
}
function Stat({label,value,green}){return <div className="stat-card"><span>{label}</span><strong className={green?'green':''}>{value}</strong></div>}
