import {useApp} from '../context/AppState';
import {useReferral} from '../context/ReferralEngine';
import {createTranslator} from '../i18n';
import {useState} from 'react';
import {useSearchParams} from 'react-router-dom';
import Icon from '../components/Icon';
export default function Premium(){const app=useApp();const [params]=useSearchParams();const [error,setError]=useState('');const checkoutMessage=params.get('checkout')==='success'?'Payment submitted. Your Premium access will activate automatically as soon as Stripe confirms the subscription.':params.get('checkout')==='cancelled'?'Checkout was cancelled. No changes were made to your account.':'';const [busy,setBusy]=useState(false);const startCheckout=async(plan)=>{setError('');setBusy(true);try{await (plan==='discount'?app.buyDiscountPremium():app.buyPremium())}catch(err){setError(err.message||'Unable to start checkout.')}finally{setBusy(false)}};const r=useReferral();const t=createTranslator(app.language);const discountAvailable=(r.monthlyDiscounts||[]).some(x=>!x.used);return <div className="page"><div className="page-top"><div><div className="eyebrow">SOLOPRO PREMIUM</div><h1>{t('moreClarity')}</h1><p className="sub">A focused monthly plan with deeper business insight, client intelligence, smart actions, declaration support and no ads.</p></div><div className="premium-price"><strong>{app.formatUsdPrice(8.99)}</strong><span>{t('monthlyOnly')}</span></div></div>
 <section className="premium-hero premium-hero-single"><div><span className="eyebrow">SOLOPRO PREMIUM</span><h2>More control over the numbers that matter.</h2><p>Everything important stays in one place: income, costs, tax reserves, clients, reports and repeatable workflows — plus Premium intelligence that turns your data into useful next steps.</p><div className="feature-row"><span><Icon name="check"/>Advanced analytics</span><span><Icon name="check"/>Client intelligence</span><span><Icon name="check"/>Smart business alerts</span><span><Icon name="check"/>No ads</span></div><button className="primary" onClick={()=>!app.isAdmin&&!app.premiumActive&&!busy&&startCheckout('premium')} disabled={app.isAdmin||app.premiumActive||busy}>{app.isAdmin?'Admin Premium — active':app.premiumActive?'Premium active':`${busy?'Opening checkout…':app.formatUsdPrice(8.99)+' / month'}`}</button></div></section>
 <div className="premium-grid"><Feature icon="chart" title="Profit Intelligence" text="Understand revenue, costs, tax reserve and estimated net result with deeper monthly trends, comparisons and practical signals."/><Feature icon="spark" title="Smart Business Assistant" text="Turn your current SoloPro numbers into useful recommendations, trend alerts and clear next steps instead of only seeing raw totals."/><Feature icon="users" title="Client Intelligence" text="Spot clients who have not returned, see your most valuable relationships and use service history for smarter follow-ups."/><Feature icon="send" title="Smart Client Messages" text="Generate ready-to-send follow-up, reminder, re-book and thank-you messages from the client history already stored in SoloPro."/><Feature icon="file" title="Tax Assistant" text="Keep the existing tax reserve calculation and get a clearer Premium view of your estimated reserve and planning position."/><Feature icon="chart" title="Advanced Earnings" text="Go beyond the basic history with monthly trends, service performance, average recorded value and clearer business comparisons."/><Feature icon="spark" title="All Styles Unlocked" text="Premium immediately unlocks all current SoloPro themes: Default, Country, Skulls, Ships and Money Rain. Referral milestones remain available for Free users."/><Feature icon="check" title="Ad-free Premium" text="Premium removes the advertising area while keeping the rest of the existing SoloPro experience intact."/></div>
 <section className="referral-offer compact-offer"><div className="offer-copy"><span className="eyebrow">REFERRAL REWARD</span><h2>{t('unlock')}</h2><p>{app.localizePrices(t('referralOffer'))}</p><small>{r.count} verified new users recorded.</small></div><div className="offer-action"><span className="old-price">{app.formatUsdPrice(8.99)} / month</span><strong>{app.formatUsdPrice(2.99)}</strong><button className="primary" disabled={app.isAdmin||!discountAvailable||busy} onClick={()=>app.isAdmin?null:startCheckout('discount')}>{discountAvailable?app.localizePrices(t('activate')):'Unlock after 7 verified referrals'}</button></div></section>{checkoutMessage&&<div className="notice">{checkoutMessage}</div>}{error&&<div className="notice">{error}</div>}
 </div>}
function Feature({icon,title,text}){return <article className="feature-card"><div className="feature-icon"><Icon name={icon} size={20}/></div><h3>{title}</h3><p>{text}</p></article>}
