import {useApp} from '../context/AppState';
import {useReferral} from '../context/ReferralEngine';
import {createTranslator} from '../i18n';
import {useState} from 'react';
import {useSearchParams,Link} from 'react-router-dom';
import Icon from '../components/Icon';
import {getSmartTrialStatus} from '../utils/smartTrial';
export default function Premium(){const app=useApp();const [params]=useSearchParams();const [error,setError]=useState('');const checkoutMessage=params.get('checkout')==='success'?'Payment submitted. Your Premium access will activate automatically as soon as Stripe confirms the subscription.':params.get('checkout')==='cancelled'?'Checkout was cancelled. No changes were made to your account.':'';const [busy,setBusy]=useState(false);const startCheckout=async(plan)=>{setError('');setBusy(true);try{await (plan==='discount'?app.buyDiscountPremium():app.buyPremium())}catch(err){setError(err.message||'Unable to start checkout.')}finally{setBusy(false)}};const r=useReferral();const t=createTranslator(app.language);const discountAvailable=(r.monthlyDiscounts||[]).some(x=>!x.used);const trial=getSmartTrialStatus(app.account?.email||app.user?.email||'');return <div className="page"><div className="page-top"><div><div className="eyebrow">SOLOPRO PREMIUM</div><h1>{t('moreClarity')}</h1><p className="sub">A focused monthly plan with deeper business insight, declaration support, client intelligence and no ads.</p></div><div className="premium-price"><strong>{app.formatUsdPrice(8.99)}</strong><span>{t('monthlyOnly')}</span></div></div>
 <section className="premium-hero premium-hero-single"><div><span className="eyebrow">SOLOPRO PREMIUM</span><h2>More control over the numbers that matter.</h2><p>Everything important stays in one place: income, costs, tax reserves, clients, reports and repeatable workflows.</p><div className="feature-row"><span><Icon name="check"/>{t('advancedAnalytics')}</span><span><Icon name="check"/>{t('unlimitedClients')}</span><span><Icon name="check"/>{t('taxHelper')}</span><span><Icon name="check"/>{t('noAds')}</span></div><button className="primary" onClick={()=>!app.isAdmin&&!app.premiumActive&&!busy&&startCheckout('premium')} disabled={app.isAdmin||app.premiumActive||busy}>{app.isAdmin?'Admin Premium — active':app.premiumActive?'Premium active':`${busy?'Opening checkout…':app.formatUsdPrice(8.99)+' / month'}`}</button></div></section>
 <section className="smart-premium-offer"><div className="smart-premium-icon"><Icon name="message" size={22}/></div><div className="smart-premium-copy"><span className="eyebrow">NEW PREMIUM FEATURE</span><h2>Smart Messages</h2><p>Keep a simple weekly client plan and let SoloPro turn the details into polished messages for WhatsApp, Telegram, Instagram, email or copy.</p><small>{trial.active?`${trial.daysLeft} days left in your one-time trial.`:trial.expired?'Your one-time 7-day trial has ended.':trial.started?'Your one-time trial is already used.':'One-time 7-day free trial for every account.'}</small></div><Link className="primary" to="/smart-messages">{trial.active?'Open Smart Messages':trial.started?'See Smart Messages':'Try for 7 days'}</Link></section>
 <div className="premium-grid"><Feature icon="chart" title={t('deeperAnalytics')} text="Understand revenue, costs, tax reserve and estimated net result with a clean monthly view."/><Feature icon="file" title={t('declarationHelper')} text="Keep declaration notes, checklists and a printable financial report ready for an accountant or your own filing workflow."/><Feature icon="users" title={t('clientIntelligence')} text="Keep client history and service records connected without tracking hours or adding unnecessary clutter."/><Feature icon="spark" title={t('animatedThemes')} text="Premium unlocks the current-country animated flag style. Referral milestones unlock three additional themes."/></div>
 <section className="referral-offer compact-offer"><div className="offer-copy"><span className="eyebrow">REFERRAL REWARD</span><h2>{t('unlock')}</h2><p>{app.localizePrices(t('referralOffer'))}</p><small>{r.count} verified new users recorded.</small></div><div className="offer-action"><span className="old-price">{app.formatUsdPrice(8.99)} / month</span><strong>{app.formatUsdPrice(2.99)}</strong><button className="primary" disabled={app.isAdmin||!discountAvailable||busy} onClick={()=>app.isAdmin?null:startCheckout('discount')}>{discountAvailable?app.localizePrices(t('activate')):'Unlock after 7 verified referrals'}</button></div></section>{checkoutMessage&&<div className="notice">{checkoutMessage}</div>}{error&&<div className="notice">{error}</div>}
 </div>}
function Feature({icon,title,text}){return <article className="feature-card"><div className="feature-icon"><Icon name={icon} size={20}/></div><h3>{title}</h3><p>{text}</p></article>}
