import {useEffect,useMemo,useState} from 'react';
import {getStoredSession} from '../utils/supabaseAuth';
import Icon from './Icon';
import ThemeCard from './ThemeCard';

const SUPABASE_URL=String(import.meta.env.VITE_SUPABASE_URL||'').replace(/\/$/,'');
const IMAGE_TYPES=['image/png','image/jpeg','image/webp','image/gif'];
const VIDEO_TYPES=['video/webm','video/mp4'];
const MAX_BYTES=4*1024*1024;
function fileData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=()=>reject(new Error('Unable to read file.'));r.readAsDataURL(file);});}
async function upload(file,token,kind,slug){if(file.size>MAX_BYTES)throw new Error(`${kind} must be 4 MB or smaller.`);const data=await fileData(file);const comma=data.indexOf(',');const bytes=Uint8Array.from(atob(data.slice(comma+1)),c=>c.charCodeAt(0));const path=`${slug}/${kind.toLowerCase()}-${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const res=await fetch(`${SUPABASE_URL}/storage/v1/object/styles/${path}`,{method:'POST',headers:{apikey:import.meta.env.VITE_SUPABASE_ANON_KEY,Authorization:`Bearer ${token}`,'Content-Type':file.type||'application/octet-stream','x-upsert':'false'},body:bytes});if(!res.ok){const d=await res.json().catch(()=>({}));throw new Error(d.message||d.error||`Unable to upload ${kind.toLowerCase()}.`);}return `${SUPABASE_URL}/storage/v1/object/public/styles/${path}`;}

export default function ThemeManager(){
 const [styles,setStyles]=useState([]);const [open,setOpen]=useState(false);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [message,setMessage]=useState('');
 const [name,setName]=useState('');const [description,setDescription]=useState('');const [type,setType]=useState('THEMATIC');const [startDate,setStartDate]=useState('');const [endDate,setEndDate]=useState('');const [image,setImage]=useState(null);const [animation,setAnimation]=useState(null);const [preview,setPreview]=useState(null);
 const token=useMemo(()=>getStoredSession()?.access_token||'',[]);
 const load=async()=>{if(!token)return;setLoading(true);try{const res=await fetch('/api/styles?admin=1',{headers:{Authorization:`Bearer ${token}`}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Unable to load styles.');setStyles(Array.isArray(data.styles)?data.styles:[]);}catch(e){setMessage(e.message||'Unable to load styles.');}finally{setLoading(false);}};
 useEffect(()=>{load();},[]);
 useEffect(()=>{if(image||animation){setPreview({name:name||'New style',image_url:image?URL.createObjectURL(image):null,animation_url:animation?URL.createObjectURL(animation):null});return()=>{if(image)URL.revokeObjectURL(preview?.image_url||'');if(animation)URL.revokeObjectURL(preview?.animation_url||'');};}setPreview(null);},[image,animation,name]);
 const reset=()=>{setName('');setDescription('');setType('THEMATIC');setStartDate('');setEndDate('');setImage(null);setAnimation(null);setPreview(null);setOpen(false);};
 const create=async()=>{if(!name.trim())return setMessage('Style name is required.');if(!image&&!animation)return setMessage('Upload an image or animation first.');setBusy('create');setMessage('');try{const slug=name.trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'').slice(0,48);const imageUrl=image?await upload(image,token,'IMAGE',slug):null;const animationUrl=animation?await upload(animation,token,'ANIMATION',slug):null;const res=await fetch('/api/styles',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({id:slug,name:name.trim(),description:description.trim(),type,image_url:imageUrl,animation_url:animationUrl,start_date:startDate||null,end_date:endDate||null})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Unable to save style.');setMessage('Style uploaded. Review it below, then publish it.');reset();await load();}catch(e){setMessage(e.message||'Unable to create style.');}finally{setBusy('');}};
 const toggle=async(style)=>{setBusy(style.id);setMessage('');try{const res=await fetch(`/api/styles?id=${encodeURIComponent(style.id)}`,{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({is_active:!style.is_active})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Unable to update style.');await load();}catch(e){setMessage(e.message||'Unable to update style.');}finally{setBusy('');}};
 const remove=async(style)=>{if(!window.confirm(`Delete ${style.name}? This removes the style from the library and it cannot be used again.`))return;setBusy(style.id);setMessage('');try{const res=await fetch(`/api/styles?id=${encodeURIComponent(style.id)}`,{method:'DELETE',headers:{Authorization:`Bearer ${token}`}});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Unable to delete style.');await load();}catch(e){setMessage(e.message||'Unable to delete style.');}finally{setBusy('');}};
 return <section className="panel admin-theme-manager"><div className="panel-head"><div><h2>Theme Manager</h2><p>Upload your own artwork or animation, preview it, then publish it for every SoloPro user.</p></div><Icon name="spark"/></div><div className="admin-theme-add"><div className="admin-theme-add-copy"><strong>Custom styles</strong><span>System styles stay protected. Only your published styles appear in Settings.</span></div><button className="primary" onClick={()=>{setOpen(v=>!v);setMessage('')}}><Icon name="spark" size={14}/>{open?'Close':'Add new style'}</button></div>
 {open&&<div className="admin-theme-form"><div className="admin-theme-form-grid"><label>Style name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Winter Night"/></label><label>Type<select value={type} onChange={e=>setType(e.target.value)}><option value="THEMATIC">Thematic</option><option value="SEASONAL">Seasonal</option><option value="MONTHLY">Monthly</option><option value="PERMANENT">Permanent</option></select></label></div><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Short description for the style."/></label>{(type==='SEASONAL'||type==='MONTHLY')&&<div className="admin-theme-form-grid"><label>Start date<input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)}/></label><label>End date<input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)}/></label></div>}<div className="admin-theme-upload"><div className="admin-theme-file"><strong>Artwork</strong><span>PNG, JPG, WebP, GIF · max 4 MB</span><input type="file" accept={IMAGE_TYPES.join(',')} onChange={e=>setImage(e.target.files?.[0]||null)}/></div><div className="admin-theme-file"><strong>Animation</strong><span>WebM or MP4 · max 4 MB</span><input type="file" accept={VIDEO_TYPES.join(',')} onChange={e=>setAnimation(e.target.files?.[0]||null)}/></div></div>{preview&&<div className="admin-theme-preview-large"><ThemeCard customStyle={preview}/></div>}<div className="admin-theme-form-actions"><button className="ghost-btn" onClick={reset}>Cancel</button><button className="primary" disabled={busy==='create'} onClick={create}>{busy==='create'?'Uploading…':'Upload & save draft'}</button></div></div>}
 {message&&<div className="notice admin-theme-notice"><Icon name="check"/>{message}</div>}
 {loading?<div className="admin-users-empty">Loading styles…</div>:styles.length===0?<div className="admin-users-empty">No custom styles yet.</div>:<div className="admin-theme-list">{styles.map(style=><div className="admin-theme-row" key={style.id}><div className="admin-theme-preview"><ThemeCard customStyle={style}/></div><div className="admin-theme-info"><strong>{style.name}</strong><span>{style.description||'Custom SoloPro style'}</span><div className="admin-theme-badges"><span className="admin-theme-badge">{style.type}</span><span className={`admin-theme-badge ${style.is_active?'live':''}`}>{style.is_active?'PUBLISHED':'DRAFT'}</span>{style.animation_url&&<span className="admin-theme-badge">ANIMATION</span>}</div></div><div className="admin-theme-actions"><button className={style.is_active?'ghost-btn':'primary'} disabled={busy===style.id} onClick={()=>toggle(style)}>{style.is_active?'Unpublish':'Publish'}</button><button className="ghost-btn" disabled={busy===style.id} onClick={()=>remove(style)}>Delete</button></div></div>)}</div>}
 </section>;
}
